import streamlit as st
import requests

# Input fields for username and password
username = st.text_input("USERNAME", value='jorgea8@hotmail.com')
password = st.text_input("PASSWORD", value='Ab12345611', type='password')

if st.button("LogIn"):
    with requests.Session() as session:
        try:

            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0',
                'Referer': 'https://www.ihg.com/rewardsclub/us/es/sign-in',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                'Accept-Language': 'en-US,en;q=0.5',
                'Accept-Encoding': 'gzip, deflate, br',
                'Connection': 'keep-alive',
            }


            # Data to be sent with the login POST request
            form_data = {
                'loginID': username,
                'password': password,
                'sessionExpiration': 0,
                'targetEnv': 'jssdk',
                'include': 'profile,data,emails,subscriptions,preferences',
                'includeUserInfo': 'true',
                'loginMode': 'standard',
                'lang': 'es',
                'APIKey': '4_jpzahMO4CBnl9Elopzfr0A',
                'source': 'showScreenSet',
                'sdk': 'js_latest',
                'authMode': 'cookie',
                'pageURL': 'https://www.ihg.com/rewardsclub/us/es/sign-in',
                'sdkBuild': 16404,
                'format': 'json',
            }

            # POST request to login with the provided credentials and cookies
            response_post = session.post('https://identity.ihg.com/accounts.login', data=form_data, headers=headers)
            
            # Displaying the response status and details
            st.write("Response Status:", response_post.status_code)
            st.write("Response Text:", response_post.text)
            
            # Check if the login was successful by analyzing the response
            if "puntos" in response_post.text:
                st.success(f"Login success for {username}.")
                
                # Display the cookies generated by the session
                new_cookies = session.cookies.get_dict()  # Get the session cookies as a dictionary
                st.write("Cookies generated for the session:")
                st.json(new_cookies)  # Display cookies in JSON format
                
            else:
                st.error(f"Login failed for {username}.")
                st.write("Response Text:", response_post.text)

        except Exception as e:
            st.error(f"An error occurred: {e}")




# st.write(response_get.text)

# https://identity.ihg.com/accounts.login
# 133661846
# 6927

# dakasengel@gmail.com
# miholiday46*

# POST
# https://identity.ihg.com/accounts.login
# loginID	"jorgea8@hotmail.com"
# password	"Ab12345611"
# sessionExpiration	"0"
# targetEnv	"jssdk"
# include	"profile,data,emails,subscriptions,preferences,"
# includeUserInfo	"true"
# loginMode	"standard"
# lang	"es"
# riskContext	'{"b0":7950,"b1":[46,49,56,36],"b2":2,"b3":["-102|1.229","-102|0.416"],"b4":3,"b5":1,"b6":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0","b7":[{"name":"PDF Viewer","filename":"internal-pdf-viewer","length":2},{"name":"Chrome PDF Viewer","filename":"internal-pdf-viewer","length":2},{"name":"Chromium PDF Viewer","filename":"internal-pdf-viewer","length":2},{"name":"Microsoft Edge PDF Viewer","filename":"internal-pdf-viewer","length":2},{"name":"WebKit built-in PDF","filename":"internal-pdf-viewer","length":2}],"b8":"10:50:14 AM","b9":420,"b10":{"state":"prompt"},"b11":false,"b12":null,"b13":[null,"1920|1080|24",false,true]}'
# APIKey	"4_jpzahMO4CBnl9Elopzfr0A"
# source	"showScreenSet"
# sdk	"js_latest"
# authMode	"cookie"
# pageURL	"https://www.ihg.com/rewardsclub/us/es/sign-in"
# sdkBuild	"16404"
# format	"json"



# _____________________________POST_____________________________
# https://identity.ihg.com/accounts.login



# _____________________________RESPONSE IN JSON_____________________________
# callId	"0fe1a5f1bda54e969b0039a75ad6be96"
# errorCode	403042
# errorDetails	"invalid loginID or password"
# errorMessage	"Invalid LoginID"
# apiVersion	2
# statusCode	403
# statusReason	"Forbidden"
# time	"2024-09-17T18:41:30.322Z"

# _____________________________REQUEST_____________________________	
# loginID	"jorgea8@hotmail.com"
# password	"Ab1234561"
# sessionExpiration	"0"
# targetEnv	"jssdk"
# include	"profile,data,emails,subscriptions,preferences,"
# includeUserInfo	"true"
# loginMode	"standard"
# lang	"es"
# riskContext	'{"b0":1764,"b1":[8,1,8,9],"b2":0,"b3":[],"b4":1,"b5":1,"b6":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0","b7":[{"name":"PDF Viewer","filename":"internal-pdf-viewer","length":2},{"name":"Chrome PDF Viewer","filename":"internal-pdf-viewer","length":2},{"name":"Chromium PDF Viewer","filename":"internal-pdf-viewer","length":2},{"name":"Microsoft Edge PDF Viewer","filename":"internal-pdf-viewer","length":2},{"name":"WebKit built-in PDF","filename":"internal-pdf-viewer","length":2}],"b8":"11:41:26 AM","b9":420,"b10":{"state":"prompt"},"b11":false,"b12":null,"b13":[null,"1920|1080|24",false,true]}'
# APIKey	"4_jpzahMO4CBnl9Elopzfr0A"
# source	"showScreenSet"
# sdk	"js_latest"
# authMode	"cookie"
# pageURL	"https://www.ihg.com/hotels/us/es/customer-care/forms/reset-password?pendingPassword=true&hideBack=true"
# sdkBuild	"16404"
# format	"json"


# _____________________________REQUEST HEADER_____________________________
	
# Accept
# 	*/*
# Accept-Encoding
# 	gzip, deflate, br, zstd
# Accept-Language
# 	en-US,en;q=0.5
# Connection
# 	keep-alive
# Content-Length
# 	1498
# Content-Type
# 	application/x-www-form-urlencoded
# Cookie
# 	_abck=B7F55D85ADAEBAAD2618959EA7BAAFF8~-1~YAAQZB0gF+7cZMSRAQAAxhlKAQxWIYSEa45v+GYZ+AI85h4uO4AqYY22KfaOouR9H9E5TBievlKjpzEYoK02AgNTbs3Xpm7BRkCjEc9QW6vVdgGSJk+OxDelkTTwd0eME4Grlsq1AZDRxf7mP9aW76r81A0e/CTjGp+FiAkPGur0sSaNEz5Yk7/woPiihuN/mVr8oA4zlCQX153BzOIQuRaIuJcnV/8eIS0JCG/rcHjM26RHIvV9j/9ZFMalfUFLJ+b6ZWG4bdeeMjHbDuhcqarYKx/+lKYveSHvb/SlabYvlhzJr8gQ5F4sQa82JHe5+oEAPIUPSzC9+x7DJkEzVfxGl+54t1ntKdo9bnCd/aEMj5jYDQWgJpsFIjTcNsBrSP4Qydbdeie7JrkumDfnN9hCd8js9e1lzdXc6bdhG39/i0MA1gt4pedz8zI28Zx/W/At63O9XjB7Nnzp9lgPI1…o7jPlIYpmIOptqSdgwqVCJwn204CIsRh38oEwC9Nz72se+4sYS2yXpJ/aDQSREcmZHJgua0oQ3yiNhEXCqrNybyDiZCSw==~1; gmid=gmid.ver4.AtLtINGTJQ.h-iJ9OoVolHDPZvKwxBCRSFIkfbMx0p7OWKZjE5O6Zil2fsRimbr74zFFB6Kj5lm.1vcrrMqpK5KbgBD33fGiQ-Fg-XTFtK3A1qhOjE_aldqvT0WGfNsoUSDIeKYeoduGKK-92a8C8I7w8eONqClbNA.sc3; ucid=0N7zTa0oWj_0p-N5j_-F4w; hasGmid=ver4; gig_bootstrap_4_jpzahMO4CBnl9Elopzfr0A=identity_ver4; ADRUM=s=1726597864895&r=https%3A%2F%2Fwww.ihg.com%2Frewardsclub%2Fus%2Fen%2Faccount-mgmt%2Fhome%3F0; PIM-SESSION-ID=u9GKImpf3T6S9HNQ
# Host
# 	identity.ihg.com
# Origin
# 	https://www.ihg.com
# Priority
# 	u=0
# Referer
# 	https://www.ihg.com/
# Sec-Fetch-Dest
# 	empty
# Sec-Fetch-Mode
# 	cors
# Sec-Fetch-Site
# 	same-site
# TE
# 	trailers
# User-Agent
# 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0








# POST
# https://www.ihg.com/rewardsclub/us/es/account-mgmt/login

# FROM DATA
# ssoTokenHeader	"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJFUTBNVVE1TjBOQ1JUSkVNemszTTBVMVJrTkRRMFUwUTBNMVJFRkJSamhETWpkRU5VRkJRZyJ9.eyJpc3MiOiJodHRwczovL2ZpZG0uZ2lneWEuY29tL2p3dC80X2pwemFoTU80Q0JubDlFbG9wemZyMEEvIiwiYXBpS2V5IjoiNF9qcHphaE1PNENCbmw5RWxvcHpmcjBBIiwiaWF0IjoxNzI2NTk4ODM2LCJleHAiOjE3MjY2MDI0MzYsInJpc2tTY29yZSI6MC4zLCJzdWIiOiIwMmQ3NjdmNS1lMjRiLTQyYzgtOTQxOC1jNDYwOWNlYTdiODciLCJmaXJzdE5hbWUiOiJFUklDSyBEQUNLVkVMIiwiZGF0YS5yY01lbWJlcnNoaXBOdW1iZXIiOiIzMzE0MjkzNzEiLCJkYXRhLm1lbWJlcktleSI6ODAwODg2MjMzfQ.JWeNkECK4-2vmsWDLPaSakcqq7CP4iLSnYZsdynGl4BgTVZoX81qnhp085usM0LaIIzan6A6yklLwZ2FCvrF9aw_TOiYk1h_0KC7xz-568WcoPJJaXsw-rzROrmMvyv3ELuy34VJblYOVnA1FaXOHZwlA3PDNLLlUYTOdDEnxrzgRwIa5thhZ3Wx7DNUXSMhSIvxbT0L62my5SUR61g_yyQS633y2JjX9kmaKlenvrl0R2YlH2HWTAZqI27thS6v_-X92fTJ5Xmui1KTzlfEw6QKBQZImDpOvv9tu42QJl1DUambgNr8R-dJmA5xbVXCN2MWB066-n2gkuur3YaMnQ"
# removeuhf	"false"
# ensightenEnabled	"true"
# fwdest	""




# COOKIES
# _abck	"B7F55D85ADAEBAAD2618959EA7BAAFF8~-1~YAAQZB0gF6vYZ8SRAQAAejNwAQy/tzaXwcVmqTj/xTGiKD3QWSTLaT3v6z7FWGQLJ7/jOSiii7OXhkXWAjo9YF1x/AVXgfRC58kra/8mTGHIZcwVnVGf/fnVtycQ5Ba3KG1E9KygkAjnLTMOLq8YVjreo/zqzEGNvyNP9Ih/Ml2COcUz8PyCamF5x97Z/b7kJBVZBUvnfdMdSGbmQ3xF6FCbRQBy+tbxvjM8xZ8p9BuanT2GCJ0KoEBtV+A6hYtQ9Z3DDeB2d+NT5/hR1NH9iKBCurlUH7L26aR8nBfv+AQ8Erjww8lAnE+ty/EtvcTnxMerFNzLjM27hNxSdAlslCpCkYa9SKY47nfz7eTsqm+MbTGEUQB7Vz8SiWLULUutQG8hkEh87FjYpC2GsovE70EhP0esFGK205W+5O+CEqYhIzuhKNVQt4IWOqzlDehkrjBMUf0+TfJYKI8UHZ/m76xlpbsB6vPSMpzH1/uQTv/OPd9iXE0NH/ddUwQuHMGNFvq+4ekDla0RFogXenXagm3/jZxxSXHMlvL4wq9wqr7CH4YLJX72eFJ0Ej4eyUsCIw2jfUBkP/4=~-1~-1~1726602611"
# ADRUM	"s=1726600910694&r=https://www.ihg.com/rewardsclub/us/es/sign-in?1606127354"
# ak_bmsc	"A8511808C1837982495A3C8B3A637808~000000000000000000000000000000~YAAQZSg0F8akVtiRAQAALgobARkmqvLJMcMCE1flmWyCXkoA7Wrn1fGOu7RyKZ+be7tBxdmSVffTTx0ZZG9mNf1TnRBe6cMaCiuz0Ai8l0CECYjxWs+gDi45aTUwecty3r0YH2/kXKsy299tHwulYGwrlOFGjgzefjt1FnREOSFhXVLk1WppfN3b7omdfdGz0KNh30UuWpvKP4+vZ/g53CprfkKKjfKDNduA9F4giwvVN6ei4ktD6VD/qCnFDHwOlDOKXlHVsr6xNOAwJFaGhVeRqwTPmXwts/ZXTHpFJPZSEL0Z+Av0RbX8yJMu3xQdJc79PKs9KustGBAfjUudjSdT3FcQf8KRX/8DrzX9symB95GmbMdv5MQmgpp372EUdJ/ylzJo"
# bm_sv	"F7247CF1F222D7DF0BAE87E5AAF5C0E1~YAAQBx0gF5RjeOyRAQAAQehvARmK2dUe72B8d8MMJNiklaQ86sAS9OurjD2x2ZQXoPgvA+pjOYJZiAkeNgdIg6D64H7Kj/PnARN5EB6iVefvVxNnqC9HhX7yzt3hzlYp/n9k2A8jE5As5b4qCXm0k4+/A6H/cM57NQXDYYYpLatQeRiIdy1QZnsVDVDYM9aMhhgCvBAteUonn5UKGMW8/C2Cwjvd8n5Ggb8ykPS7D1vCaMpjw/eTC1lnsedwHw==~1"
# bm_sz	"F2716AF0D58E388370897584441F4C5A~YAAQZB0gF+PRZ8SRAQAAbbtvARm0VA4slSJWKgEak2MJrE6AoLwRBIAQ2HeKCLCs3DMUEDvp5Quihj6z5IhV//nbiySEpGNrU4UXjtOSSPBXj6nKcz9X6jPJDdQACPnbqKdjiyboTAYbCR6p5TT/eHWInILV8QlLCCpTtvC+DFCnFDEhUyO0nFTg5oF9kT5SBivUyLRtetJHxX9xvYjK35YWXCi0ZLV5wm9FE9yrRXiSN7G/I2CZ0pYfNam9u1QIb/O82aSJ0E7dIY1vYN6gd7zn2OrPzZloFmqe80MyKhv+FuR4fv6RMr9b8l/yrtfMXr2n37EORTGjw0pxRZ4kS4tvfunw1sJmKxKTFS/nNzFHVEkljfo99C74wo1fhiIpNZZeqlmm8ti8X+GB57LFVLzB9GYsI6kr1nUx/vPcefavgLg9Tf1aIiul001MJeAsY/H3q/55CN06hVs8V2Qk3KYKHiCYnr4B4tzjC4MR2MZrv9aIdrxL65fg8Hm+aC9px7tfsrDAXUh7ASf3mG8LPv4jqWkPtw7yGXhSpXM=~4339509~4473153"
# gig_bootstrap_4_jpzahMO4CBnl9Elopzfr0A	"identity_ver4"
# gmid	"gmid.ver4.AtLtINGTJQ.h-iJ9OoVolHDPZvKwxBCRSFIkfbMx0p7OWKZjE5O6Zil2fsRimbr74zFFB6Kj5lm.1vcrrMqpK5KbgBD33fGiQ-Fg-XTFtK3A1qhOjE_aldqvT0WGfNsoUSDIeKYeoduGKK-92a8C8I7w8eONqClbNA.sc3"
# hasGmid	"ver4"
# PIM-SESSION-ID	"u9GKImpf3T6S9HNQ"
# ucid	"0N7zTa0oWj_0p-N5j_-F4w"
# X-IHG-SSO-TOKEN	"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJFUTBNVVE1TjBOQ1JUSkVNemszTTBVMVJrTkRRMFUwUTBNMVJFRkJSamhETWpkRU5VRkJRZyJ9.eyJpc3MiOiJodHRwczovL2ZpZG0uZ2lneWEuY29tL2p3dC80X2pwemFoTU80Q0JubDlFbG9wemZyMEEvIiwiYXBpS2V5IjoiNF9qcHphaE1PNENCbmw5RWxvcHpmcjBBIiwiaWF0IjoxNzI2NTk5Nzc2LCJleHAiOjE3MjY1OTk3NzcsInN1YiI6IjAyZDc2N2Y1LWUyNGItNDJjOC05NDE4LWM0NjA5Y2VhN2I4NyIsImZpcnN0TmFtZSI6IkVSSUNLIERBQ0tWRUwiLCJkYXRhLnJjTWVtYmVyc2hpcE51bWJlciI6IjMzMTQyOTM3MSIsImRhdGEubWVtYmVyS2V5Ijo4MDA4ODYyMzN9.Pyqo63LngJJebo6sRmYjPnTL39gRk14chdXjN-46AIWpu0ru1W05AKQNshYdU6qYSDAdZtbOT2H7MDtYsWr3D8yuI5Y4tP98wMel_qyiJOMTCPdvk8HGzo-4yfcrHyHlPoVeE04YMsDpc6F3cJj2M0nS4av3cNRjZtLbS2U0Bwr-N1994B6_y2dTUspOupbhEISXIlL1Pw0YP8YAusaVw-6lu_LV3gFnEC6XQgzvTwOXYZ1UDmWTqZyxf0EtnIHiK1H8M7Q9Px2o2MvJ6C92jqWI2T3g-7hk_b5sLYK6SsUJ-Wb1hnVxCgUZISi5SZHXaDlsRjU6CckTo9Y45Bc2pw"